---
- hosts: checkbox
  remote_user: ubuntu
  vars:
        ansible_ssh_private_key_file: /home/ubuntu/DevOps.pem
        ansible_python_interpreter: /usr/bin/python3
  vars_files: 
    - variables.yml 
  connection: ssh
  environment:
      AWS_ACCESS_KEY_ID: ""
      AWS_SECRET_ACCESS_KEY: ""
    # KUBE_URL: "{{externalIP}}"

  roles:
    - deployCheckbox
