---
- hosts: kube
#  become: true
  remote_user: ubuntu 
  vars: 
    ansible_ssh_private_key_file: /home/ubuntu/devops2.pem
    ansible_python_interpreter: /usr/bin/python3 
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
#    host_key_checking: false
    NAME: kubeservice.k8s.local
  connection: ssh
  environment:
      NAME: kubeservice.k8s.local
      KOPS_STATE_STORE: s3://kube-service-store
      
  roles:
    - kubeservice



  
